/*CREACION DE TABLAS RECYCLON*/
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE BANCOS CASCADE CONSTRAINTS; 
DROP TABLE COBROS CASCADE CONSTRAINTS;
DROP TABLE PAGOS CASCADE CONSTRAINTS;
DROP TABLE PROVEEDORES CASCADE CONSTRAINTS;


CREATE TABLE CLIENTES(
ID NUMBER(5) CONSTRAINT PK_EMPLEADOS PRIMARY KEY,
NOMBRE VARCHAR2(40) CONSTRAINT EMP_NOMBRE UNIQUE NOT NULL,
NCUENTA VARCHAR(24) CONSTRAINT EMP_CUENTA UNIQUE
);

CREATE TABLE PROVEEDORES(
ID NUMBER(5) CONSTRAINT PK_PROVEEDOR PRIMARY KEY,
NOMBRE VARCHAR2(40) CONSTRAINT PRO_NOMBRE UNIQUE NOT NULL
);

CREATE TABLE BANCOS(
ID NUMBER(5) CONSTRAINT PK_BANCO PRIMARY KEY,
NOMBRE VARCHAR2(40) CONSTRAINT BAN_NOMBRE UNIQUE NOT NULL
);

CREATE TABLE PAGOS(
ID NUMBER(5) CONSTRAINT PK_PAGO PRIMARY KEY,
IDPROVEEDOR NUMBER(5)CONSTRAINT FK_IDPROV_PAGO REFERENCES PROVEEDORES,
IDBANCO NUMBER(5)CONSTRAINT FK_IDBAN_PAGO REFERENCES BANCOS,
IMPORTE NUMBER(8,2) CONSTRAINT NN_IMPORTE NOT NULL,
NUMFACTURA NUMBER(6),
FECHAVENCIMIENTO DATE,
FORMAPAGO VARCHAR2(25),
ESTADO NUMBER(1) CONSTRAINT CHK_ESTADO_P CHECK (ESTADO IN(0,1))
);

CREATE TABLE COBROS(
ID NUMBER(5) CONSTRAINT PK_COBRO PRIMARY KEY,
IDCLIENTE NUMBER(5)CONSTRAINT FK_IDCLI_COBRO REFERENCES CLIENTES,
IDBANCO NUMBER(5)CONSTRAINT FK_IDBAN_COBRO REFERENCES BANCOS,
IMPORTE NUMBER(8,2),
NUMFACTURA NUMBER(6),
FECHA DATE,
FORMAPAGO VARCHAR2(25),
ESTADO NUMBER(1) CONSTRAINT CHK_ESTADO_C CHECK (ESTADO IN(0,1))
);